print("##############################")
print("#                            #")
print("#   Hilman Azhar Al-Faqih    #")
print("#       2610817110017        #")
print("#                            #")
print("##############################")